create schema if not exists private;

create table if not exists public.ejazati_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  role text not null default 'user' check (role in ('owner','user')),
  status text not null default 'active' check (status in ('active','disabled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ejazati_leave_settings (
  user_id uuid primary key references public.ejazati_profiles(id) on delete cascade,
  base_balance integer not null default 30 check (base_balance >= 0),
  carried_balance integer not null default 0 check (carried_balance >= 0),
  carry_expiry date,
  weekend_days smallint[] not null default array[6,0]::smallint[],
  updated_at timestamptz not null default now()
);

create table if not exists public.ejazati_leaves (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.ejazati_profiles(id) on delete cascade,
  leave_type text not null default 'annual' check (leave_type in ('annual','sick','emergency','unpaid','mission','other')),
  title text,
  start_date date not null,
  end_date date not null,
  deduct_from_balance boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ejazati_leaves_date_check check (end_date >= start_date)
);
create index if not exists ejazati_leaves_user_dates_idx on public.ejazati_leaves(user_id,start_date,end_date);

create table if not exists public.ejazati_holidays (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.ejazati_profiles(id) on delete cascade,
  holiday_date date not null,
  name text not null,
  created_at timestamptz not null default now(),
  unique(user_id,holiday_date,name)
);

create table if not exists public.ejazati_app_versions (
  id bigint generated by default as identity primary key,
  version text not null unique,
  channel text not null default 'beta' check (channel in ('beta','production')),
  status text not null default 'testing' check (status in ('testing','approved','published','rejected')),
  release_notes text,
  created_by uuid references public.ejazati_profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  published_at timestamptz
);

create table if not exists public.ejazati_user_version_state (
  user_id uuid primary key references public.ejazati_profiles(id) on delete cascade,
  current_version text,
  dismissed_version text,
  updated_at timestamptz not null default now()
);

create table if not exists public.ejazati_backup_history (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.ejazati_profiles(id) on delete cascade,
  backup_kind text not null default 'manual' check (backup_kind in ('manual','pre_update')),
  app_version text,
  created_at timestamptz not null default now()
);

create or replace function private.ejazati_is_active()
returns boolean language sql stable security definer set search_path=''
as $$select exists(select 1 from public.ejazati_profiles p where p.id=(select auth.uid()) and p.status='active')$$;

create or replace function private.ejazati_is_owner()
returns boolean language sql stable security definer set search_path=''
as $$select exists(select 1 from public.ejazati_profiles p where p.id=(select auth.uid()) and p.role='owner' and p.status='active')$$;

revoke all on function private.ejazati_is_active() from public;
revoke all on function private.ejazati_is_owner() from public;
grant usage on schema private to authenticated;
grant execute on function private.ejazati_is_active() to authenticated;
grant execute on function private.ejazati_is_owner() to authenticated;

create or replace function public.ejazati_claim_owner()
returns boolean language plpgsql security definer set search_path=''
as $$
declare caller uuid := (select auth.uid());
begin
  if caller is null then raise exception 'Authentication required'; end if;
  if exists(select 1 from public.ejazati_profiles where role='owner') then return false; end if;
  update public.ejazati_profiles set role='owner',status='active',updated_at=now() where id=caller;
  return found;
end;
$$;
revoke all on function public.ejazati_claim_owner() from public,anon;
grant execute on function public.ejazati_claim_owner() to authenticated;

create or replace function private.handle_ejazati_new_user()
returns trigger language plpgsql security definer set search_path=''
as $$
begin
  insert into public.ejazati_profiles(id,email,display_name)
  values(new.id,new.email,coalesce(new.raw_user_meta_data->>'display_name',split_part(coalesce(new.email,''),'@',1)))
  on conflict(id) do nothing;
  insert into public.ejazati_leave_settings(user_id) values(new.id) on conflict(user_id) do nothing;
  insert into public.ejazati_user_version_state(user_id,current_version) values(new.id,'1.0.0') on conflict(user_id) do nothing;
  return new;
end;
$$;
revoke all on function private.handle_ejazati_new_user() from public;

drop trigger if exists on_auth_user_created_ejazati on auth.users;
create trigger on_auth_user_created_ejazati after insert on auth.users
for each row execute function private.handle_ejazati_new_user();

alter table public.ejazati_profiles enable row level security;
alter table public.ejazati_leave_settings enable row level security;
alter table public.ejazati_leaves enable row level security;
alter table public.ejazati_holidays enable row level security;
alter table public.ejazati_app_versions enable row level security;
alter table public.ejazati_user_version_state enable row level security;
alter table public.ejazati_backup_history enable row level security;

create policy ejazati_profiles_select on public.ejazati_profiles for select to authenticated
using((select auth.uid())=id or (select private.ejazati_is_owner()));

create policy ejazati_settings_all on public.ejazati_leave_settings for all to authenticated
using((select private.ejazati_is_active()) and (select auth.uid())=user_id)
with check((select private.ejazati_is_active()) and (select auth.uid())=user_id);

create policy ejazati_leaves_all on public.ejazati_leaves for all to authenticated
using((select private.ejazati_is_active()) and (select auth.uid())=user_id)
with check((select private.ejazati_is_active()) and (select auth.uid())=user_id);

create policy ejazati_holidays_all on public.ejazati_holidays for all to authenticated
using((select private.ejazati_is_active()) and (select auth.uid())=user_id)
with check((select private.ejazati_is_active()) and (select auth.uid())=user_id);

create policy ejazati_versions_read on public.ejazati_app_versions for select to authenticated
using((select private.ejazati_is_active()) and (status='published' or (select private.ejazati_is_owner())));

create policy ejazati_versions_owner_insert on public.ejazati_app_versions for insert to authenticated
with check((select private.ejazati_is_owner()) and created_by=(select auth.uid()));

create policy ejazati_versions_owner_update on public.ejazati_app_versions for update to authenticated
using((select private.ejazati_is_owner())) with check((select private.ejazati_is_owner()));

create policy ejazati_user_version_all on public.ejazati_user_version_state for all to authenticated
using((select private.ejazati_is_active()) and (select auth.uid())=user_id)
with check((select private.ejazati_is_active()) and (select auth.uid())=user_id);

create policy ejazati_backup_all on public.ejazati_backup_history for all to authenticated
using((select private.ejazati_is_active()) and (select auth.uid())=user_id)
with check((select private.ejazati_is_active()) and (select auth.uid())=user_id);

grant select,insert,update,delete on public.ejazati_profiles,public.ejazati_leave_settings,public.ejazati_leaves,
 public.ejazati_holidays,public.ejazati_app_versions,public.ejazati_user_version_state,public.ejazati_backup_history to authenticated;
grant usage,select on sequence public.ejazati_app_versions_id_seq to authenticated;

insert into public.ejazati_app_versions(version,channel,status,release_notes)
values('1.0.0','production','published','الإصدار الأول من إجازاتي')
on conflict(version) do nothing;
